FROM debian:stretch 

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils \
    && apt-get install -y iproute2 \
    && apt-get install -y net-tools \
    && apt-get install -y iputils-ping \
    && apt-get install -y isc-dhcp-client \
    && apt-get install -y nano \
    && apt-get install -y openssh-server \
    && apt-get install -y openssh-client \
    #&& apt-get install -y macchanger \
    && apt-get install -y sudo \
    #&& apt-get install -y apache2 \
    && apt-get install -y iptables \
    && apt-get install -y curl 

WORKDIR /home/pc4
ADD mac.sh /home/pc4/mac.sh
RUN chmod 777 /home/pc4/mac.sh

