FROM debian:latest

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils \
    && apt-get install -y iproute2 \
    && apt-get install -y net-tools \
    && apt-get install -y iputils-ping \
    && apt-get install -y isc-dhcp-client \
    && apt-get install -y nano \
    && apt-get install -y openssh-server \
    && apt-get install -y openssh-client \
    && apt-get install -y sudo \
    && apt-get install -y iptables \
    && apt-get install -y curl

WORKDIR /home/pc5
ADD mac.sh /home/pc5/mac.sh
RUN chmod 700 /home/pc5/mac.sh



